# -*- coding: utf-8 -*-
"""Zen_of_Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQBRizlukGbYcRc0hITdjBlvhKpTCSmp
"""

import this