# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqZpSMgOySMcbLI5I7c8ANPCJszl9k8w
"""

print('Printing the elements at odd indices.')

print([i for i in range(10)])

a = 0
for i in range(10):
    if i == 2:
        pass
    else:
        a = i
        print(a)

# Sum of numbers upto 10.

sum = 0 
i = 10
while i > 0:
    sum += i
    i -= 1

print(sum)

def map (array, method):
    result = []
    for element in array:
        value = method(element)
    return result

x = ['1', '2', '15', '-7', '300']
y = sorted(x)
print(y)

arr = [7, 5, 4, 23, 12]

def func(arr):
    temp = 0
    for x in arr:
        if  x % 2 ==1:
            temp += 1
        else:
            temp = 0
        if temp == 3:
            return True
    return False

func(arr)

f = lambda n : 1 if n <= 1 else n * f (n-1)

g = f(4)

print(g)

import math
d = -5.1
print(math.floor(d))

def f1(a):
    if a == 0:
        return 1
    return a * f1(a-1)

f2 = lambda a , b: abs (2*a-3*b)

print(f1(f2(2, 3)))